spring:
  application:
    # 服务名称
    name: gateway
  cloud:
    nacos:
      # 注册中心
      discovery:
        server-addr: 127.0.0.1:8848
    # sentinel dashboard监听
    sentinel:
      transport:
        # 任意指定一个端口供dashboard监听（此应用作为一个服务端提供接口）
        port: 8102
        # sentinel dashboard启动的端口
        dashboard: 127.0.0.1:8080
    # 网关配置
    gateway:
      # gateway可以实现通过IP路由到指定服务，如果想通过`服务名`路由则需要和discover`注册中心`结合
      discovery:
        locator:
          enabled: true
      # 路由规则
      routes:
        - id: NACOS-CONSUMER
          # `lb`采用LoadBalanceClient方式请求
          uri: lb://nacos-consumer
          # 对于不同的场景，可以自定义某种请求规则，比如配置`Method`限定请求方法，不能为空
          predicates:
            - Path=/test
        - id: NACOS-PROVIDER
          uri: lb://nacos-provider
          predicates:
            - Path=/provider/**


#feign:
#  # 开启Feign对sentinel的支持
#  sentinel:
#    enabled: true

# 服务端口
server:
  port: 8090

# 监听端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
